config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  root to: 'static#home'

  resources :owners do
      resources :records do
          resources :nodes
      end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/node.rb
class Node < ApplicationRecord
  belongs_to :record
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :records
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :owner
  has_many :nodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
    def new
        @node = Node.new
        @record = Record.find(params[:record_id])
    end

    def create
        @node = Node.new(node_params)
        @node.record = Record.find(params[:record_id])

        if (@node.referenceNodeId)
            parent_node = Node.find(@node.referenceNodeId)

            if @node.nodeNumber > parent_node.nodeNumber
                redirect_to root_path
            else
                if @node.save!
                    redirect_to root_path
                end

            end
        else

                if @node.save!
                    redirect_to root_path
                end

        end

    end

    def show

    end
end

def node_params
    params.require(:node).permit(:data,:nodeNumber,:referenceNodeId)
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
    def new
        @record = Record.new
    end

    def create
        @record = Record.new(record_params)
        @record.owner = current_owner
        if @record.save!
            redirect_to new_owner_record_path
        end
    end

    def show
        @record = Record.find(params[:id])
        @node = Node.new
    end

end


private

def record_params
    params.require(:record).permit(:name)
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posisttest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nodes/new.html.erb
<%=form_for([current_owner,@record,@node]) do |f|%>
    <%=f.label :nodeNumber%>
    <%=f.number_field :nodeNumber%>
    <%=f.label :data%>
    <%=f.text_field :data%>

    </br>
    <h5>Leave empty if genesis</h5>
    <%=f.label :referenceNodeId%>
    <%=f.number_field :referenceNodeId%>

    <%=f.submit "Create"%>
<%end%>
</br>
</br>
</br>
<h2>Your nodes:</h2>

<%if @record.nodes%>
    <%@record.nodes.each do |node|%>
        <%if node.owner == current_owner%>
            Data:<%= node.data%>
    <%else%>
        Data: <%=(0..50).map { ('a'..'z').to_a[rand(26)]}.join%>
    <%end%>
    </br>
    Number:<%=node.nodeNumber%>
</br>
ID:<%=node.id%>
</br>
<%if node.referenceNodeId%>
    Parent Node: <%=node.referenceNodeId%>
<%else%>
    Is Genesis node
<%end%>
</br>
</br>
</br>
    <%end%>
    </br>
<%end%>

app/views/records/new.html.erb
Form for new record ->
<%=form_for([current_owner,@record]) do |f|%>
    <%=f.label :name%>
    <%=f.text_field :name%>
    <%=f.submit "Create"%>
<%end%>

<hr>
Your older records:

<% current_owner.records.each do |record|%>
    <%=link_to record.name,owner_record_path(record.owner,record)%>
    </br>
<%end%>

app/views/records/show.html.erb
<%= @record.name %>
<hr>
<%=link_to "Create a node",new_owner_record_node_path(@record.owner,@record,@node)%>